sonar.projectKey=glair-vision-go
sonar.projectName=glair-vision-go
sonar.projectVersion=0.0.1

sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=examples/**,vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.language=go
